name: goreleaser

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true
        default: "v0.0.0"
      version:
        description: "Version"
        required: true
        default: "0.0.0"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Tests with Coverage
        run: |
          go test -v -coverprofile=coverage.out.tmp ./...
          cat coverage.out.tmp | grep -v "_mock.go" > coverage.out
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out -o coverage.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a ${{ github.event.inputs.tag }} -m "Release ${{ github.event.inputs.tag }}"
          git push origin ${{ github.event.inputs.tag }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: dbm
          path: dist/*
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.html
